import { test } from 'node:test'
import assert from 'node:assert/strict'
import { renderBootstrapVbs } from '../lib/render-vbs.js'

test('quotes both paths and passes the start mode', () => {
  const vbs = renderBootstrapVbs({
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    serviceJsPath: 'C:\\Users\\me\\.dsh\\profiles\\web\\node_modules\\dsh-autostart\\service.js',
  })
  assert.match(
    vbs,
    /sh\.Run """C:\\Program Files\\nodejs\\node\.exe"" ""C:\\Users\\me\\\.dsh\\profiles\\web\\node_modules\\dsh-autostart\\service\.js"" start", 0, False/,
  )
})

test('uses a hidden window and does not wait', () => {
  const vbs = renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js' })
  assert.match(vbs, /, 0, False$/)
})

test('carries a do-not-edit banner', () => {
  const vbs = renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js' })
  assert.match(vbs, /Generated by dsh-autostart/)
})

test('rejects missing input', () => {
  assert.throws(() => renderBootstrapVbs({ serviceJsPath: 'b.js' }), /execPath/)
  assert.throws(() => renderBootstrapVbs({ execPath: 'a.exe' }), /serviceJsPath/)
})
