import { test } from 'node:test'
import assert from 'node:assert/strict'
import { renderBootstrapVbs } from '../lib/render-vbs.js'

const CONFIG = 'C:\\Users\\me\\.dsh\\dsh-autostart\\config.json'

test('quotes every path and passes the start mode with an explicit config', () => {
  // --config matters at login too, not just on the restart path: if DSH_HOME is
  // only session-scoped (set by whatever launched DSH, not persisted in
  // HKCU\Environment), wscript inherits an environment without it, the helper
  // re-derives ~/.dsh, exits 1, and autostart silently does nothing.
  const vbs = renderBootstrapVbs({
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    serviceJsPath: 'C:\\Users\\me\\.dsh\\profiles\\web\\node_modules\\dsh-autostart\\service.js',
    configPath: CONFIG,
  })
  assert.match(
    vbs,
    /sh\.Run """C:\\Program Files\\nodejs\\node\.exe"" ""C:\\Users\\me\\\.dsh\\profiles\\web\\node_modules\\dsh-autostart\\service\.js"" start --config ""C:\\Users\\me\\\.dsh\\dsh-autostart\\config\.json""", 0, False/,
  )
})

test('uses a hidden window and does not wait', () => {
  const vbs = renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js', configPath: CONFIG })
  assert.match(vbs, /, 0, False$/)
})

test('carries a do-not-edit banner', () => {
  const vbs = renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js', configPath: CONFIG })
  assert.match(vbs, /Generated by dsh-autostart/)
})

test('rejects missing input', () => {
  assert.throws(() => renderBootstrapVbs({ serviceJsPath: 'b.js', configPath: CONFIG }), /execPath/)
  assert.throws(() => renderBootstrapVbs({ execPath: 'a.exe', configPath: CONFIG }), /serviceJsPath/)
  assert.throws(() => renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js' }), /configPath/)
})

test('rejects a relative config path', () => {
  // wscript starts in an arbitrary working directory, so a relative path would
  // resolve somewhere else entirely.
  assert.throws(
    () =>
      renderBootstrapVbs({ execPath: 'a.exe', serviceJsPath: 'b.js', configPath: 'rel\\config.json' }),
    /absolute/,
  )
})
