// Render the windowless boot entry point.
//
// wscript.exe creates no console window, which is the whole reason this file
// exists: `powershell -WindowStyle Hidden` on a long-running script still
// produced a visible empty console window.
const CRLF = '\r\n'

/** Quote one argument for a VBS string literal (embedded quotes are doubled). */
function quoteForVbs(value) {
  return `"${String(value).replace(/"/g, '""')}"`
}

/**
 * @param input.execPath - absolute path of the node executable.
 * @param input.serviceJsPath - absolute path of this package's service.js.
 * @returns the full bootstrap.vbs content.
 */
export function renderBootstrapVbs(input) {
  const { execPath, serviceJsPath } = input ?? {}
  if (typeof execPath !== 'string' || execPath === '') {
    throw new Error('renderBootstrapVbs: execPath is required')
  }
  if (typeof serviceJsPath !== 'string' || serviceJsPath === '') {
    throw new Error('renderBootstrapVbs: serviceJsPath is required')
  }
  const command = `${quoteForVbs(execPath)} ${quoteForVbs(serviceJsPath)} start`
  return [
    "' Generated by dsh-autostart. Do not edit by hand.",
    'Set sh = CreateObject("WScript.Shell")',
    `sh.Run ${quoteForVbs(command)}, 0, False`,
  ].join(CRLF)
}
