// Render the windowless boot entry point.
//
// wscript.exe creates no console window, which is the whole reason this file
// exists: `powershell -WindowStyle Hidden` on a long-running script still
// produced a visible empty console window.
import path from 'node:path'

const CRLF = '\r\n'

/** Quote one argument for a VBS string literal (embedded quotes are doubled). */
function quoteForVbs(value) {
  return `"${String(value).replace(/"/g, '""')}"`
}

/**
 * @param input.execPath - absolute path of the node executable.
 * @param input.serviceJsPath - absolute path of this package's service.js.
 * @param input.configPath - absolute path of config.json, passed explicitly so the
 *   login helper never re-derives the DSH home. If DSH_HOME is only session-scoped
 *   (set by whatever launched DSH rather than persisted in HKCU\Environment), the
 *   login environment has none: the helper would fall back to ~/.dsh, exit 1, and
 *   autostart would silently do nothing.
 * @returns the full bootstrap.vbs content.
 */
export function renderBootstrapVbs(input) {
  const { execPath, serviceJsPath, configPath } = input ?? {}
  if (typeof execPath !== 'string' || execPath === '') {
    throw new Error('renderBootstrapVbs: execPath is required')
  }
  if (typeof serviceJsPath !== 'string' || serviceJsPath === '') {
    throw new Error('renderBootstrapVbs: serviceJsPath is required')
  }
  if (typeof configPath !== 'string' || configPath === '') {
    throw new Error('renderBootstrapVbs: configPath is required')
  }
  if (!path.win32.isAbsolute(configPath)) {
    throw new Error(
      `renderBootstrapVbs: configPath must be absolute, got ${configPath} (wscript starts in an arbitrary working directory)`,
    )
  }
  const command = `${quoteForVbs(execPath)} ${quoteForVbs(serviceJsPath)} start --config ${quoteForVbs(configPath)}`
  return [
    "' Generated by dsh-autostart. Do not edit by hand.",
    'Set sh = CreateObject("WScript.Shell")',
    `sh.Run ${quoteForVbs(command)}, 0, False`,
  ].join(CRLF)
}
